[package]
name = "nexus-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Tipos y structs DB compatibles con schema Odoo 19 (NexusTech ERP)"

[dependencies]
serde        = { workspace = true }
serde_json   = { workspace = true }
anyhow       = { workspace = true }
thiserror    = { workspace = true }
tracing      = { workspace = true }
sqlx         = { workspace = true }
chrono       = { workspace = true }
rust_decimal = { workspace = true }
uuid         = { workspace = true }
