[package]
name = "nexus-py"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Interoperabilidad CPython con PyO3 sobre nexus-orm"

[lib]
name = "_nexus"
crate-type = ["rlib", "cdylib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.22" }
nexus-orm = { path = "../nexus-orm" }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "uuid", "chrono", "rust_decimal"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
